spring:
  application:
    name: @project.name@
  output:
    ansi.enabled: always
  data:
    mongodb:
      auto-index-creation: true
logging:
  level:
    root: INFO
    org.springframework.web.reactive.function.client: WARN

springdoc:
  swagger-ui.path: /docs

server:
  port: 8101

app:
  version: @project.version@
  name: @project.name@

gios:
  base-url: "https://api.gios.gov.pl/pjp-api"

n8n:
  base-url: "localhost:8081/"