spring:
  config:
    import: file:///G:/javaProjects/CONFIG/nature-service/nature-service-application.yml

  data:
    mongodb:
      host: localhost
      port: 27019
      database: nature-service_mongo_db
      username: ${MONGO_USER}
      password: ${MONGO_PWD}
      authentication-database: admin
      auto-index-creation: true
logging:
  level:
    root: INFO
    com.emat.reapi.ai.configuration: DEBUG
    org.springframework.web.reactive.function.client: TRACE

scheduler:
  airquality:
    cron: "0 */2 * * * *"
    duration: 500
  weather:
    cron: "0 30 0/3 * * *"

n8n:
  base-url: "http://192.168.50.34:5678/webhook-test"