spring:
  management:
    endpoints:
      web:
        exposure:
          include: health,info,logfile
    endpoint:
      logfile:
        enabled: true
      health:
        probes:
          enabled: true
        show-details: never
  logging:
    file:
      name: /app/logs/nature-service.log
    level:
      root: INFO
      org.springframework.web.reactive.function.client: WARN
  config:
    import: optional:file:/config/nature-service-application.yml
  #    in docker, mounted from server file path in opt/

logging:
  level:
    root: INFO
    com.emat.reapi.ai.configuration: DEBUG
    org.springframework.web.reactive.function.client: TRACE